name: 'claude'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<3.0.0"]

models:
  claude:
    +schema: claude_reports
    +materialized: table
    intermediate:
      +materialized: ephemeral
      +schema: claude_staging
    staging:
      +schema: claude_staging
      +materialized: view
      tmp:
        +materialized: view

vars:
  claude:
    claude_using_cost_report: true
    claude_using_enterprise_user_cost_report: true
    claude_using_message_usage_report: true
    claude_using_enterprise_user_usage_report: true
    claude_using_claude_code_usage_report: true
    claude_using_claude_code_usage_report_model_breakdown: true
    claude_using_users: true
    claude_using_enterprise_user_actor: true
    claude_using_api_key: true
    claude_using_enterprise_user_activity: true
    claude__enterprise_user_activity_pass_through_metrics: []
