{% macro get_enterprise_user_activity_columns() %}

{% set columns = [
    {"name": "date",                                                               "datatype": "date"},
    {"name": "user_id",                                                            "datatype": dbt.type_string()},
    {"name": "chat_metrics_connectors_used_count",                                 "datatype": dbt.type_int()},
    {"name": "chat_metrics_distinct_artifacts_created_count",                      "datatype": dbt.type_int()},
    {"name": "chat_metrics_distinct_conversation_count",                           "datatype": dbt.type_int()},
    {"name": "chat_metrics_distinct_files_uploaded_count",                         "datatype": dbt.type_int()},
    {"name": "chat_metrics_distinct_projects_created_count",                       "datatype": dbt.type_int()},
    {"name": "chat_metrics_distinct_projects_used_count",                          "datatype": dbt.type_int()},
    {"name": "chat_metrics_distinct_shared_artifacts_viewed_count",                "datatype": dbt.type_int()},
    {"name": "chat_metrics_distinct_skills_used_count",                            "datatype": dbt.type_int()},
    {"name": "chat_metrics_message_count",                                         "datatype": dbt.type_int()},
    {"name": "chat_metrics_shared_conversations_viewed_count",                     "datatype": dbt.type_int()},
    {"name": "chat_metrics_thinking_message_count",                                "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_core_metrics_commit_count",                      "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_core_metrics_distinct_session_count",            "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_core_metrics_lines_of_code_added_count",         "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_core_metrics_lines_of_code_removed_count",       "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_core_metrics_pull_request_count",                "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_tool_actions_edit_tool_accepted_count",          "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_tool_actions_edit_tool_rejected_count",          "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_tool_actions_multi_edit_tool_accepted_count",    "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_tool_actions_multi_edit_tool_rejected_count",    "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_tool_actions_notebook_edit_tool_accepted_count", "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_tool_actions_notebook_edit_tool_rejected_count", "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_tool_actions_write_tool_accepted_count",         "datatype": dbt.type_int()},
    {"name": "claude_code_metrics_tool_actions_write_tool_rejected_count",         "datatype": dbt.type_int()},
    {"name": "cowork_metrics_action_count",                                        "datatype": dbt.type_int()},
    {"name": "cowork_metrics_connectors_used_count",                               "datatype": dbt.type_int()},
    {"name": "cowork_metrics_dispatch_turn_count",                                 "datatype": dbt.type_int()},
    {"name": "cowork_metrics_distinct_connectors_used_count",                      "datatype": dbt.type_int()},
    {"name": "cowork_metrics_distinct_session_count",                              "datatype": dbt.type_int()},
    {"name": "cowork_metrics_distinct_skills_used_count",                          "datatype": dbt.type_int()},
    {"name": "cowork_metrics_message_count",                                       "datatype": dbt.type_int()},
    {"name": "cowork_metrics_skills_used_count",                                   "datatype": dbt.type_int()},
    {"name": "design_metrics_distinct_projects_created_count",                     "datatype": dbt.type_int()},
    {"name": "design_metrics_distinct_projects_used_count",                        "datatype": dbt.type_int()},
    {"name": "design_metrics_distinct_session_count",                              "datatype": dbt.type_int()},
    {"name": "design_metrics_message_count",                                       "datatype": dbt.type_int()},
    {"name": "office_metrics_excel_connectors_used_count",                         "datatype": dbt.type_int()},
    {"name": "office_metrics_excel_distinct_connectors_used_count",                "datatype": dbt.type_int()},
    {"name": "office_metrics_excel_distinct_session_count",                        "datatype": dbt.type_int()},
    {"name": "office_metrics_excel_distinct_skills_used_count",                    "datatype": dbt.type_int()},
    {"name": "office_metrics_excel_message_count",                                 "datatype": dbt.type_int()},
    {"name": "office_metrics_excel_skills_used_count",                             "datatype": dbt.type_int()},
    {"name": "office_metrics_outlook_connectors_used_count",                       "datatype": dbt.type_int()},
    {"name": "office_metrics_outlook_distinct_connectors_used_count",              "datatype": dbt.type_int()},
    {"name": "office_metrics_outlook_distinct_session_count",                      "datatype": dbt.type_int()},
    {"name": "office_metrics_outlook_distinct_skills_used_count",                  "datatype": dbt.type_int()},
    {"name": "office_metrics_outlook_message_count",                               "datatype": dbt.type_int()},
    {"name": "office_metrics_outlook_skills_used_count",                           "datatype": dbt.type_int()},
    {"name": "office_metrics_powerpoint_connectors_used_count",                    "datatype": dbt.type_int()},
    {"name": "office_metrics_powerpoint_distinct_connectors_used_count",           "datatype": dbt.type_int()},
    {"name": "office_metrics_powerpoint_distinct_session_count",                   "datatype": dbt.type_int()},
    {"name": "office_metrics_powerpoint_distinct_skills_used_count",               "datatype": dbt.type_int()},
    {"name": "office_metrics_powerpoint_message_count",                            "datatype": dbt.type_int()},
    {"name": "office_metrics_powerpoint_skills_used_count",                        "datatype": dbt.type_int()},
    {"name": "office_metrics_word_connectors_used_count",                          "datatype": dbt.type_int()},
    {"name": "office_metrics_word_distinct_connectors_used_count",                 "datatype": dbt.type_int()},
    {"name": "office_metrics_word_distinct_session_count",                         "datatype": dbt.type_int()},
    {"name": "office_metrics_word_distinct_skills_used_count",                     "datatype": dbt.type_int()},
    {"name": "office_metrics_word_message_count",                                  "datatype": dbt.type_int()},
    {"name": "office_metrics_word_skills_used_count",                              "datatype": dbt.type_int()},
    {"name": "web_search_count",                                                   "datatype": dbt.type_int()},
    {"name": "_fivetran_deleted",                                                  "datatype": "boolean"},
    {"name": "_fivetran_synced",                                                   "datatype": dbt.type_timestamp()}
] %}

{{ return(columns) }}

{% endmacro %}
